# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - backappqa

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

    #  - name: npm install, build, and test
    #    run: |
    #      npm install
    #      npm run build --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backappqa'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_52C91ACC17CB4157912C4518CF09258C }}

  devtest:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Checkout Test Repository (Public)
        uses: actions/checkout@v4
        with:
          repository: 'IQA-App/ui-tests'  
          ref: main  

      - name: Install dependencies for Playwright tests
        run: |
          cd ui-tests  
          npm ci  
          npx playwright install --with-deps 

      - name: Run Playwright Tests
        run: |
          cd ui-tests  
          npm test  
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          UI_BASE_URL: ${{ secrets.UI_BASE_URL }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SERVERPORT: ${{ secrets.SERVERPORT }}
          EMAIL_PREFIX: ${{ secrets.EMAIL_PREFIX }}
          EMAIL_DOMAIN: ${{ secrets.EMAIL_DOMAIN }}
          CI_RUN: true

      - name: Upload Playwright Reports
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ui-tests/playwright-report/  
          retention-days: 30

      - name: Attach Artifacts on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Test Artifacts
          path: ui-tests/test-results/  

      - name: Deploy Playwright Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          publish_dir: ui-tests/playwright-report  